server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/microservice2
#    username: root
#    password: root
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
